version: "3"

services:

  ################# HADOOP ######################### 

  namenode:
    image: rootcl/hadoop-namenode
    restart: always
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"
  datanode:
    image: rootcl/hadoop-datanode
    restart: always
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"

  ################# HIVE ######################### 

  hive-server:
    image:  rootcl/hive-postgresql
    container_name: hive-server
    restart: always
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
  hive-metastore:
    container_name: hive-metastore
    image: rootcl/hive-postgresql
    restart: always
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
  hive-metastore-postgresql:
    container_name: hive-metastore-postgresql
    image: rootcl/hive-metastore-postgresql
    restart: always


  ############### HUE ######################

  huedb:
    image: rootcl/postgres12
    container_name: huedb-postgresql
    volumes:
      - huedb:/var/lib/postgresl/data/
    ports:
      - "5432"
      - "5000"
    env_file:
      - ./hive.env
    environment:
        SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432 hive-metastore:9083"

  hue:
    image: rootcl/hue
    container_name: hue
    environment:
        SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432 hive-metastore:9083 huedb-postgresql:5000"
    ports:
      - "8879:8888"
    volumes:
      - ./hue-overrides.ini:/usr/share/hue/desktop/conf/hue-overrides.ini
    links:
      - huedb
      - hive-server


volumes:
  namenode:
  datanode:
  huedb: